version: "3"

services:
  vscode:
    image: vscode
    build: ./vscode
    environment:
      DISPLAY: host.docker.internal:0
    network_mode: host
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp.X11-unix
