#!/bin/bash

# https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap
add-apt-repository ppa:saiarcot895/chromium-beta -y

apt-get update
sudo apt remove chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra -y
apt-get install -y wget gpg xterm software-properties-common python3 pip chromium-browser vim rustc cargo

# install the jupyter assets
pip install jupyterlab 
pip install notebook 
pip install voila

# machine learning tooling
pip install torch torchvision
pip install pandas

# install the LLM tools 
pip install langchain
pip install openai
pip install gpt-index

adduser --disabled-password --gecos "" jupyter
mv runjupyter /home/jupyter/
mv chromium /usr/bin/

mkdir /home/jupyter/notebooks
chown -R jupyter.jupyter /home/jupyter

su - jupyter -c "cd /home/jupyter; ./runjupyter"
echo "hanging in ./install"
while true; do sleep 30; done;
