#!/bin/bash

apt-get update
apt-get install -y wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg
apt install -y apt-transport-https
apt update
apt install -y code 

adduser --disabled-password --gecos "" vscode
mv runvscode /home/vscode/




#su - vscode -c "DISPLAY=host.docker.internal:0 code --no-sandbox --verbose"

su - vscode -c "cd /home/vscode; ./runvscode"
while true; do sleep 30; done;
